version: "3"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://paola-calcic-saundra.ngrok-free.dev
      - N8N_EDITOR_BASE_URL=https://paola-calcic-saundra.ngrok-free.dev
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Karachi
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: